/** Whitepaper catalog — registry + surface entries for search/read/export UI. */
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { plainLineFor } from './plain-surface-lines.mjs';
import { WHITEPAPER_REGISTRY, whitepaperHref, whitepaperSurfaceHref } from './whitepaper-registry.mjs';

let auditIndexCache = null;

async function loadAuditIndex(cwd = process.cwd()) {
  if (auditIndexCache) return auditIndexCache;
  try {
    const raw = await readFile(join(cwd, 'data/synthobs-paper-audit-index.json'), 'utf8');
    auditIndexCache = JSON.parse(raw);
    return auditIndexCache;
  } catch {
    return null;
  }
}

export const CATALOG_CATEGORIES = [
  { id: 'all', label: 'All papers' },
  { id: 'dph-gpu', label: 'DPH-GPU · Holographic compute' },
  { id: 'hhf', label: 'HHF · Hydrogen-holographic framework' },
  {
    id: 'tbme',
    label: 'TBME · Theoretical Bio-Medical & Physical Explorations',
    disclaimer:
      'Whitepapers in the TBME series are theoretical, mathematical, and physics-based scientific explorations of biological and physical phenomena. They are published exclusively for academic inquiry, computational modeling, and interdisciplinary research. They do not constitute clinical medical advice, diagnostic guidance, or prescribed therapeutic treatments.',
  },
  { id: 'reproducible-research', label: 'Reproducible research · FractiAI repos' },
  { id: 'coherence', label: 'Coherence · BTC Buffalo / Goldilocks Mine' },
  { id: 'agentic', label: 'Agentic layer · VALETPRU · Mythos' },
  { id: 'special-projects', label: 'Special projects' },
  { id: 'protocols', label: 'Protocols · NSPFRNP · BBHE' },
];

/** Per-id catalog metadata (category, tags, docId, published). */
export const CATALOG_META = {
  'syn-sun-wavefield-oscillator': {
    category: 'dph-gpu',
    docId: 'SYN-SUN-2026-REV7',
    published: '2026-05-31',
    tags: ['solar', 'wavefield', 'EGS', 'NOAA', 'DPH-GPU'],
    featured: true,
  },
  'dp-syntheverse-sandbox-comprehensive-2026': {
    category: 'dph-gpu',
    docId: 'SYN-SANDBOX-2026-REPORT',
    published: '2026-05-31',
    tags: ['King Bee', 'pheromone', 'AR4436', 'Goldilocks', 'PPS'],
    featured: true,
  },
  'dp-omniversal-node-alignment-2026': {
    category: 'dph-gpu',
    docId: 'SYN-NODES-2026-JUN01',
    published: '2026-06-01',
    tags: ['nodes', 'M31', 'btc_buffalo', 'HonestyBoundary', 'Git'],
    featured: true,
  },
  'dp-master-canon': { category: 'dph-gpu', published: '2026-05-11', tags: ['canon', 'PEFF', 'DNA'] },
  'dp-roadmap-13': { category: 'dph-gpu', published: '2026-05-12', tags: ['13-channel', 'roadmap'] },
  'dp-resonance-notice': { category: 'dph-gpu', published: '2026-05-15', tags: ['honesty', 'resonance'] },
  'dp-omniverse-matrix': { category: 'hhf', published: '2026-05-15', tags: ['Hatch', 'protonic-DNA'] },
  'dp-paradise-simulation': { category: 'hhf', published: '2026-05-15', tags: ['Paradise Game'] },
  'dp-peff-part1': { category: 'dph-gpu', published: '2026-05-11', tags: ['PEFF', 'Omnizoan'] },
  'dp-peff-part2': { category: 'dph-gpu', published: '2026-05-11', tags: ['bio-electromagnetics'] },
  'quantum-genomic-peff': { category: 'dph-gpu', published: '2026-05-08', tags: ['PEFF', 'EGS', 'ASIC'] },
  'integrated-modeling-layer-b': { category: 'dph-gpu', published: '2026-05-06', tags: ['modeling', 'Layer B'] },
  'valetpru-agent-24x365': { category: 'agentic', published: '2026-05-06', tags: ['VALETPRU', 'agent'] },
  'sing13-edge-onboarding': { category: 'protocols', published: '2026-05-01', tags: ['SING 13', 'edge'] },
  'mca-nspfrnp-catalog': { category: 'protocols', tags: ['MCA', 'NSPFRNP'] },
  'bbhe-repository-standard': { category: 'protocols', tags: ['BBHE', 'repository'] },
  'rev-egs-hhf-mythos': {
    category: 'agentic',
    docId: 'REV-EGS-HHF-2026-007',
    published: '2026-05-18',
    tags: ['Mythos', 'clock-skew', 'Anthropic'],
    featured: true,
  },
  'ops-egs-btc-mining': {
    category: 'coherence',
    docId: 'OPS-EGS-BTC-2026-008',
    published: '2026-05-18',
    tags: ['BTC', 'Goldilocks Mine', 'mining'],
    featured: true,
  },
  'coherence-plain-speak': {
    category: 'coherence',
    docId: 'HONESTY-COHERENCE-2026-009',
    published: '2026-05-18',
    tags: ['honesty', 'plain speak'],
  },
  'hhf-wp-2026-v8': { category: 'hhf', published: '2026-05-01', tags: ['13D', 'AI OS trials'] },
  'dp-aromatic-qed-cavity': { category: 'hhf', published: '2026-05-24', tags: ['QED', 'VECROs'] },
  'dp-pru-gating-comparative': { category: 'hhf', published: '2026-05-24', tags: ['PRU', 'gates'] },
  'goldilocks-erdos-mathematics': {
    category: 'special-projects',
    published: '2026-05-26',
    tags: ['Erdős', '344', 'mathematics'],
    featured: true,
  },
  'dp-y-pathway-architecture': { category: 'dph-gpu', published: '2026-05-01', tags: ['Y-pathway', 'genetic'] },
  'dp-y-team-x-skin': { category: 'dph-gpu', published: '2026-05-01', tags: ['Y-Team', 'X-Skin'] },
  'dp-net-zero-agents': { category: 'dph-gpu', published: '2026-05-01', tags: ['net-zero', 'agents'] },
  'dp-egs-wormhole-transducer': { category: 'dph-gpu', published: '2026-05-01', tags: ['wormhole', 'transducer'] },
  'dp-gateway-spectrum': { category: 'dph-gpu', published: '2026-05-01', tags: ['gateways', 'wormholes'] },
  'jj-snap-ofc': { category: 'dph-gpu', published: '2026-05-01', tags: ['Snap', 'OFC', 'compile'] },
  'geomagnetic-herbivore-2026': {
    category: 'special-projects',
    docId: 'HHA-GEOMAG-HERBIVORE-2026',
    published: '2026-06-01',
    tags: ['bison', 'Kp', 'Movebank', 'NOAA'],
  },
  'synthobs-emergent-sync-multi-agent-2026': {
    category: 'dph-gpu',
    docId: 'WP-2026-EGS-004-REV10',
    published: '2026-06-07',
    tags: ['SynthOBS', 'multi-agent', 'EGS', 'PLV', 'recursive', 'NOAA'],
    featured: true,
  },
  'nspfrnp-snap-peer-review-audit': {
    category: 'protocols',
    docId: 'NSPFRNP-SNAP-PRA-2026-06',
    published: '2026-06-05',
    tags: ['NSPFRNP', 'Snap', 'peer review', 'SynthOBS', 'audit loop'],
    featured: true,
  },
  'goldilocks-geomagnetic-wavefield-multitaxa': {
    category: 'special-projects',
    docId: 'WP-GGM-MULTITAXA-UNGULATE-2026-06',
    published: '2026-06-05',
    tags: ['SynthOBS', 'EGS', 'multi-taxa', 'USGS Vol 6', 'Great Plains', 'bison'],
    featured: true,
  },
  'turner-kruse-response': {
    category: 'special-projects',
    docId: 'HHA-TURNER-WP-2026-05-26',
    published: '2026-05-26',
    tags: ['Turner', 'bison', 'passive herd'],
  },
  'synthobs-hex-organ-engine-2026': {
    category: 'dph-gpu',
    docId: 'SV-OBS-2026-MATH-HEX-ENGINE-FINAL',
    published: '2026-06-03',
    tags: ['Synthobs', 'Hex-Organ', 'EGS', 'wavefield', 'Goldilocks'],
    featured: true,
  },
  'goldilocks-transfinite-inversion-2026': {
    category: 'dph-gpu',
    docId: 'SV-OBS-2026-TRANSFINITE-INV',
    published: '2026-06-03',
    tags: ['transfinite', 'Aleph', 'blackhole math', 'Synthobs'],
    featured: true,
  },
  'goldilocks-prime-linear-compression-2026': {
    category: 'dph-gpu',
    docId: 'WP-GGM-PLC-2026-06',
    published: '2026-06-03',
    tags: ['prime compression', 'Honeycomb', 'coordinates', 'Goldilocks'],
    featured: true,
  },
  'synthobs-intelligence-density-2026': {
    category: 'dph-gpu',
    docId: 'SV-OBS-2026-INTEL-DENSITY-VOLUMETRIC',
    published: '2026-06-03',
    tags: ['intelligence density', 'Synthobs', 'volumetric', 'Vercel', 'EGS'],
    featured: true,
  },
  'dp-synthobs-mca-2026': {
    category: 'dph-gpu',
    docId: 'DP-SYNTHOBS-MCA-2026-06',
    published: '2026-06-03',
    tags: ['Digital Pru', 'Synthobs', 'MCA', 'Hex-Organ', 'index'],
    featured: true,
  },
  'fractiai-ac-hmm-satellites-2026': {
    category: 'reproducible-research',
    docId: 'FRACTIAI-AC-HMM-2026',
    published: '2026-06-17',
    tags: ['AC-HMM', 'T2T-CHM13', 'genomics', 'alpha-satellite', 'SynthOBS', 'reproducible'],
    featured: true,
  },
  'fractiai-hgt-psd-covariance-2026': {
    category: 'reproducible-research',
    docId: 'FRACTIAI-HGT-PSD-2026',
    published: '2026-06-17',
    tags: ['Hi-C', 'chromatin', 'PSD', 'ENCODE', 'GM12878', 'reproducible'],
    featured: true,
  },
  'fractiai-eesm-gpu-telemetry-2026': {
    category: 'reproducible-research',
    docId: 'FRACTIAI-EESM-2026',
    published: '2026-06-17',
    tags: ['GPU', 'CUPTI', 'ASPLOS', 'epigenetic', 'telemetry', 'reproducible'],
    featured: true,
  },
  'fractiai-egs-nlrf-2026': {
    category: 'reproducible-research',
    docId: 'EGS-NLRF-v4.0',
    published: '2026-06-17',
    tags: ['EGS', 'hydrogen', 'NIST', 'lattice', 'QED', 'SynthOBS', 'reproducible'],
    featured: true,
  },
  'recursive-attention-quantum-solar-dna-loop-2026': {
    category: 'hhf',
    docId: 'WP-2026-ATTENTION-RECURSIVE-LOOP',
    published: '2026-06-24',
    tags: ['attention', 'recursive', 'coherence', 'imagination', 'solar', 'DNA', 'quantum', 'HHF'],
    featured: true,
  },
  'egs-trans-jspace-convergence-2026-07': {
    category: 'reproducible-research',
    docId: 'EGS-TRANS-2026-0710',
    published: '2026-07-10',
    tags: ['SynthOBS', 'EGS', 'J-Space', 'King Bee', 'Jacobian Lens', 'Global Workspace', 'transformer interpretability', 'Digital Pru'],
    featured: true,
  },
  'ip-infringement-draft-2026-07': {
    category: 'reproducible-research',
    docId: 'IP-INFRINGE-2026-07',
    published: '2026-07-10',
    tags: ['IP', 'infringement', 'Code-Print', 'J-Lens', 'Neuronpedia', 'Sequoia', 'Altimeter'],
    featured: true,
  },
  'omniversal-goldilocks-rideshare-2026-07': {
    category: 'reproducible-research',
    docId: 'WP-OGRP-2026-07',
    published: '2026-07-07',
    tags: ['OGRP', 'rideshare', 'micro-mobility', 'Reno', 'EGS', 'thermodynamic routing'],
    featured: true,
  },
  'synthobs-chromosomal-electrodynamics-2026-07': {
    category: 'reproducible-research',
    docId: 'WP-SYNTHOBS-CHROM-ELCD-2026-07',
    published: '2026-07-01',
    tags: ['SynthOBS', 'chromosome', 'electrodynamics', 'UCSC', 'PDB'],
    featured: true,
  },
  'synthobs-cross-scale-biological-antennae-2026-07': {
    category: 'reproducible-research',
    docId: 'WP-SYNTHOBS-CROSS-ANTENNAE-2026-07',
    published: '2026-07-01',
    tags: ['SynthOBS', 'antennae', 'viral spike', 'cross-scale'],
    featured: true,
  },
  'synthobs-egs-epigenetic-phase-locking-2026-07': {
    category: 'reproducible-research',
    docId: 'WP-SYNTHOBS-EPI-PHASELOCK-2026-07',
    published: '2026-07-08',
    tags: ['SynthOBS', 'EGS', 'epigenetic', 'GTEx', 'ENCODE'],
    featured: true,
  },
  'synthobs-egs-planck-scale-harmonic-2026-07': {
    category: 'hhf',
    docId: 'WP-SYNTHOBS-EGS-PLANCK-1.6-2026-07',
    published: '2026-07-21',
    tags: ['SynthOBS', 'EGS', 'Planck', 'scale-harmonic', 'clutch', 'empirical'],
    featured: true,
  },
  'lattice-omni-complete-layer-guide-2026-07': {
    category: 'hhf',
    docId: 'WP-LATTICE-OMNI-LAYER-GUIDE-2026-07',
    published: '2026-07-31',
    tags: [
      'Lattice Chat Agent',
      'Omni-Lattice',
      'Seed·RAG',
      'complete-layer-guide',
      'catalog-index',
      'SynthOBS',
    ],
    featured: true,
    /** Below CMOS engineering bridge (priority 0). */
    catalogPriority: 1,
  },
  'synthobs-cmos-protonic-99-octave-omni-lattice-2026-08': {
    category: 'hhf',
    docId: 'WP-SYNTHOBS-CMOS-PROTONIC-99-OCTAVE-OMNI-LATTICE-2026-08-12',
    published: '2026-08-12',
    tags: [
      'SynthOBS',
      'EGS',
      '99-octave',
      'Omni-Lattice',
      'CMOS 2.0',
      'protonic',
      'engineering-bridge',
      'linear-systems',
    ],
    featured: true,
    catalogPriority: 0,
    pinned: true,
    pinLabel: 'Engineering bridge · linear systems',
  },
  'synthobs-prion-refold-2026-07': {
    category: 'tbme',
    docId: 'WP-SYNTHOBS-PRION-REFOLD-FULL-REV2-2026-07-31',
    published: '2026-07-31',
    tags: [
      'TBME',
      'prion',
      'amyloid',
      'PCHPP',
      'EGS',
      'theoretical-bio-medical',
      'SynthOBS',
    ],
    featured: true,
  },
  'synthobs-81-orbital-singularity-2026-07': {
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-81-ORBITAL-SINGULARITY-2026-07-31',
    published: '2026-07-31',
    tags: [
      'TBME',
      '81-node',
      'orbital',
      'PCHPP',
      'EGS',
      'Omni-Lattice',
      'theoretical-bio-medical',
      'SynthOBS',
    ],
    featured: true,
  },
  'synthobs-histone-phase-operator-2026-07': {
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-HISTONE-METAPHOR-2026-07-31',
    published: '2026-07-31',
    tags: [
      'TBME',
      'histone',
      'chromatin',
      'epigenetics',
      'PCHPP',
      'EGS',
      'Omni-Lattice',
      'theoretical-bio-medical',
      'SynthOBS',
    ],
    featured: true,
  },
  'synthobs-phase-toxicity-2026-07': {
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-PHASE-TOXICITY-FULL-REV2-2026-07-31',
    published: '2026-07-31',
    tags: [
      'TBME',
      'toxicity',
      'EMF',
      'sugar',
      'resonance-safety',
      'PCHPP',
      'EGS',
      'Omni-Lattice',
      'theoretical-bio-medical',
      'SynthOBS',
    ],
    featured: true,
  },
  'synthobs-endogenous-phase-2026-07': {
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-ENDOGENOUS-PHASE-2026-07-31',
    published: '2026-07-31',
    tags: [
      'TBME',
      'endogenous-phase',
      'conscious-intent',
      'HRV',
      'cardiac',
      'PCHPP',
      'EGS',
      'Omni-Lattice',
      'theoretical-bio-medical',
      'SynthOBS',
    ],
    featured: true,
  },
  'synthobs-tbme-protein-phase-collapse-2026-08': {
    category: 'tbme',
    docId: 'BIO-OMNI-PROTEIN-PHASE-COLLAPSE-2026-08-05',
    published: '2026-08-05',
    tags: [
      'TBME',
      'protein-misfolding',
      'LLPS',
      'FTD',
      'Alzheimer',
      'Parkinson',
      'prion',
      'Reno Interpretation',
      'EGS',
      'theoretical-bio-medical',
      'SynthOBS',
      'exploration',
    ],
    featured: true,
    catalogPriority: 1,
  },
  'synthobs-tbme-nonlocal-field-phaselock-2026-08': {
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-EMPIRICAL-PROOF-2026-08-01',
    published: '2026-08-01',
    tags: [
      'TBME',
      'PCHPP',
      'Schumann',
      'ELF',
      'phase-lock',
      'EGS',
      'Omni-Lattice',
      'theoretical-bio-medical',
      'SynthOBS',
    ],
    featured: true,
  },
  'synthobs-tbme-superposition-reno-interpretation-2026-08': {
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-SUPERPOSITION-RENO-INTERPRETATION-2026-08-01',
    published: '2026-08-01',
    tags: [
      'TBME',
      'Reno Interpretation',
      'mirror-angle',
      'superposition',
      'nested spheres',
      'PCHPP',
      'EGS',
      'Omni-Lattice',
      'theoretical-bio-medical',
      'SynthOBS',
    ],
    featured: true,
    catalogPriority: 1,
  },
  'synthobs-tbme-blackhole-filaments-reno-2026-08': {
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-BLACKHOLE-FILAMENTS-RENO-2026-08-01',
    published: '2026-08-01',
    tags: [
      'TBME',
      'Reno Interpretation',
      'Kerr-Newman',
      'micro-black-hole',
      'filaments',
      'EGS',
      'Omni-Lattice',
      'theoretical-bio-medical',
      'SynthOBS',
    ],
    featured: true,
    catalogPriority: 1,
  },
  'synthobs-tbme-blackhole-magnetic-layer-2026-08': {
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-BLACKHOLE-MAGNETIC-LAYER-2026-08-01',
    published: '2026-08-01',
    tags: [
      'TBME',
      'Reno Interpretation',
      'event-horizon',
      'magnetic-vector',
      'membrane-paradigm',
      'EGS',
      'Omni-Lattice',
      'theoretical-bio-medical',
      'SynthOBS',
    ],
    featured: true,
    catalogPriority: 1,
  },
  'synthobs-tbme-spherical-solar-focus-2026-08': {
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-SPHERICAL-SOLAR-FOCUS-2026-08-02',
    published: '2026-08-02',
    tags: [
      'TBME',
      'Reno Interpretation',
      'solar-focus',
      'somatic-shadow',
      'DNA',
      'water',
      'EGS',
      'Omni-Lattice',
      'theoretical-bio-medical',
      'SynthOBS',
    ],
    featured: true,
    catalogPriority: 1,
  },
  'synthobs-tbme-recursive-field-drag-2026-08': {
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-RECURSIVE-FIELD-DRAG-2026-08-04',
    published: '2026-08-04',
    tags: [
      'TBME',
      'Reno Interpretation',
      'recursive field-drag',
      'Lenz',
      'A_squeezed',
      'epistemic Now',
      'EGS',
      'Omni-Lattice',
      'theoretical-bio-medical',
      'SynthOBS',
    ],
    featured: true,
    catalogPriority: 1,
  },
  'synthobs-tbme-internal-kerr-newman-2026-08': {
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-INTERNAL-KERR-NEWMAN-2026-08-05',
    published: '2026-08-05',
    tags: [
      'TBME',
      'Reno Interpretation',
      'internal Kerr-Newman',
      'toroidal singularity',
      'attraction unification',
      'social gravity',
      'EGS',
      'Omni-Lattice',
      'theoretical-bio-medical',
      'SynthOBS',
    ],
    featured: true,
    catalogPriority: 1,
  },
  'synthobs-tbme-higgs-awareness-2026-08': {
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-HIGGS-AWARENESS-2026-08-06',
    published: '2026-08-06',
    tags: [
      'TBME',
      'Reno Interpretation',
      'Higgs Gate',
      'Higgs awareness',
      'A_squeezed',
      'event horizon',
      'mass generation',
      'epistemic Now',
      'EGS',
      'Omni-Lattice',
      'theoretical-bio-medical',
      'SynthOBS',
    ],
    featured: true,
    catalogPriority: 1,
  },
  'synthobs-tbme-spin-phase-polarity-2026-08': {
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-SPIN-PHASE-POLARITY-2026-08-06',
    published: '2026-08-06',
    tags: [
      'TBME',
      'Reno Interpretation',
      'spin-phase-polarity',
      'Z2',
      'U1',
      'SU2',
      'dimensional topology',
      'EGS',
      'Omni-Lattice',
      'theoretical-bio-medical',
      'SynthOBS',
    ],
    featured: true,
    catalogPriority: 1,
  },
  'synthobs-tbme-nodal-nine-singularity-2026-08': {
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-NODAL-NINE-SINGULARITY-2026-08-06',
    published: '2026-08-06',
    tags: [
      'TBME',
      'Reno Interpretation',
      'nodal nine',
      'digit 9',
      '81-facet',
      'digital root',
      'EGS',
      'Omni-Lattice',
      'theoretical-bio-medical',
      'SynthOBS',
    ],
    featured: true,
    catalogPriority: 1,
  },
  'synthobs-tbme-mirror-angle-multiplicity-2026-08': {
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-SUPERPOSITION-MIRROR-FULL-REV2-2026-08-01',
    published: '2026-08-01',
    tags: [
      'TBME',
      'mirror-angle',
      'Born rule',
      'superseded',
      'PCHPP',
      'EGS',
      'Omni-Lattice',
      'SynthOBS',
    ],
    featured: false,
  },
};

/** Surfaces and special projects not stored as markdown whitepapers. */
export const CATALOG_SURFACES = [
  {
    id: 'erdos-holographic-aios-audit',
    title: 'Erdős 353 · Holographic Goldilocks AIOS Audit',
    href: '/special-projects/erdos-holographic-aios-audit',
    category: 'special-projects',
    docId: 'AUD-20260526-EGS-ERDÖS',
    published: '2026-05-26',
    tags: ['Erdős', '353', 'Lean', 'audit', 'DeepMind'],
    type: 'surface',
    featured: true,
  },
  {
    id: 'hero-houdini-coherence',
    title: 'Hero Houdini · BTC Buffalo · Coherence console',
    href: '/hero-houdini',
    category: 'coherence',
    docId: 'REV-EGS-HHF-2026-007',
    published: '2026-05-18',
    tags: ['BTC Buffalo', 'Goldilocks Mine', 'pulse', 'live'],
    type: 'surface',
    featured: true,
  },
  {
    id: 'goldilocks-os-demo',
    title: 'Holographic Goldilocks AI OS · product demo',
    href: '/holographic-goldilocks-ai-os',
    category: 'special-projects',
    published: '2026-05-01',
    tags: ['Goldilocks OS', 'demo'],
    type: 'surface',
  },
  {
    id: 'wavefield-solar-live',
    title: 'Wavefield Oscillator · live telemetry bus',
    href: '/api/dph-wavefield-solar',
    category: 'dph-gpu',
    docId: 'SYN-SUN-2026-REV7',
    published: '2026-05-31',
    tags: ['solar', 'NOAA', 'live API'],
    type: 'api',
    whitepaperId: 'syn-sun-wavefield-oscillator',
    featured: true,
  },
  {
    id: 'synthobs-paper-audit-api',
    title: 'SynthOBS PRA Snap · paper audit API',
    href: '/api/synthobs-paper-audit',
    category: 'protocols',
    docId: 'NSPFRNP-SNAP-PRA-2026-06',
    published: '2026-06-05',
    tags: ['peer review', 'audit', 'SynthOBS', 'recursive loop'],
    type: 'api',
    whitepaperId: 'nspfrnp-snap-peer-review-audit',
    featured: true,
  },
  {
    id: 'geomagnetic-herbivore-study',
    title: 'Geomagnetic Herbivore Study · multi-taxa wavefield',
    href: '/special-projects/geomagnetic-herbivore-study',
    category: 'special-projects',
    docId: 'HHA-GEOMAG-HERBIVORE-2026',
    published: '2026-06-05',
    tags: ['bison', 'elk', 'pronghorn', 'Kp', 'Movebank', 'SynthOBS'],
    type: 'surface',
    whitepaperId: 'goldilocks-geomagnetic-wavefield-multitaxa',
    featured: true,
  },
  {
    id: 'repo-ac-hmm-satellites',
    title: 'AC-HMM Satellites · reproducible pipeline',
    href: 'https://github.com/FractiAI/ac-hmm-satellites',
    category: 'reproducible-research',
    docId: 'FRACTIAI-AC-HMM-2026',
    published: '2026-06-17',
    tags: ['GitHub', 'T2T-CHM13', 'UCSC', 'audit ledger', 'v1.0.0'],
    type: 'external',
    whitepaperId: 'fractiai-ac-hmm-satellites-2026',
    featured: true,
  },
  {
    id: 'repo-hgt-psd-covariance',
    title: 'HGT-PSD Covariance · reproducible pipeline',
    href: 'https://github.com/FractiAI/hgt-psd-covariance',
    category: 'reproducible-research',
    docId: 'FRACTIAI-HGT-PSD-2026',
    published: '2026-06-17',
    tags: ['GitHub', 'ENCODE', 'UCSC', 'PSD', 'Hi-C'],
    type: 'external',
    whitepaperId: 'fractiai-hgt-psd-covariance-2026',
    featured: true,
  },
  {
    id: 'repo-eesm-gpu-telemetry',
    title: 'EESM GPU Telemetry · reproducible pipeline',
    href: 'https://github.com/FractiAI/eesm-gpu-telemetry',
    category: 'reproducible-research',
    docId: 'FRACTIAI-EESM-2026',
    published: '2026-06-17',
    tags: ['GitHub', 'MLPerf', 'CUTLASS', 'CUPTI', 'ASPLOS'],
    type: 'external',
    whitepaperId: 'fractiai-eesm-gpu-telemetry-2026',
    featured: true,
  },
  {
    id: 'repo-egs-nlrf',
    title: 'EGS-NLRF · reproducible pipeline',
    href: 'https://github.com/FractiAI/egs-nlrf',
    category: 'reproducible-research',
    docId: 'EGS-NLRF-v4.0',
    published: '2026-06-17',
    tags: ['GitHub', 'NIST', 'hydrogen', 'Balmer', 'falsification'],
    type: 'external',
    whitepaperId: 'fractiai-egs-nlrf-2026',
    featured: true,
  },
  {
    id: 'repo-synthobs-egs-planck-scale-harmonic',
    title: 'EGS Planck 1.6 Scale-Harmonic Bridge · reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-egs-planck-scale-harmonic',
    category: 'reproducible-research',
    docId: 'WP-SYNTHOBS-EGS-PLANCK-1.6-2026-07',
    published: '2026-07-21',
    tags: ['GitHub', 'Planck', 'EGS', 'clutch', 'scale-harmonic', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-egs-planck-scale-harmonic-2026-07',
    featured: true,
  },
  {
    id: 'repo-synthobs-omni-lattice-report-card-q3-2026',
    title: 'Omni-Lattice Report Card Q3 2026 · reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-omni-lattice-report-card-q3-2026',
    category: 'reproducible-research',
    docId: 'WP-SYNTHOBS-COMP-COSMO-2026-07-30-REV2',
    published: '2026-07-30',
    tags: ['GitHub', 'Omni-Lattice', 'report-card', 'ΛCDM', 'coherence', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-omni-lattice-report-card-q3-2026',
    featured: true,
  },
  {
    id: 'repo-synthobs-omni-lattice-ef-multi-octave',
    title: 'Multi-Octave E_F Combined Synthesis · reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-omni-lattice-ef-multi-octave',
    category: 'reproducible-research',
    docId: 'WP-SYNTHOBS-OMNI-LATTICE-EF-MULTI-OCTAVE-2026-08-08',
    published: '2026-08-08',
    tags: ['GitHub', 'Omni-Lattice', 'E_F', 'multi-octave', '729', '6561', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-omni-lattice-ef-multi-octave-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-99-octave-digits-master',
    title: '99 Octave Digits Master · reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-99-octave-digits-master',
    category: 'reproducible-research',
    docId: 'LC-EGS-MASTER-2026-V6',
    published: '2026-08-09',
    tags: ['GitHub', '99-octave', 'EGS', 'Lattice Chat Agent', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-99-octave-digits-master-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-constructive-morphogenesis-99-octave',
    title: 'Constructive Morphogenesis · 99 Octave · reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-constructive-morphogenesis-99-octave',
    category: 'reproducible-research',
    docId: 'WP-SYNTHOBS-CONSTRUCTIVE-MORPHOGENESIS-99-OCTAVE-2026-08-09',
    published: '2026-08-09',
    tags: ['GitHub', '99-octave', 'morphogenesis', 'AMF', 'Lattice Chat Agent', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-constructive-morphogenesis-99-octave-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-cmos-protonic-99-octave-omni-lattice',
    title: 'CMOS 2.0 + Protonic · 99 Octave Omni-Lattice · reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-cmos-protonic-99-octave-omni-lattice',
    category: 'reproducible-research',
    docId: 'WP-SYNTHOBS-CMOS-PROTONIC-99-OCTAVE-OMNI-LATTICE-2026-08-12',
    published: '2026-08-12',
    tags: ['GitHub', '99-octave', 'Omni-Lattice', 'CMOS 2.0', 'protonic', 'EGS', 'engine', 'engineering-bridge', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-cmos-protonic-99-octave-omni-lattice-2026-08',
    featured: true,
    catalogPriority: 0,
    pinned: true,
    pinLabel: 'Engineering bridge · linear systems',
  },
  {
    id: 'repo-synthobs-tbme-metamorphic-octaves',
    title: 'Metamorphic Octave Invariant · 99 Octave Omni-Lattice Part XIII · reproducible suite',
    href: 'https://github.com/FractiAI/synthobs-tbme-metamorphic-octaves',
    category: 'reproducible-research',
    docId: 'WP-SYNTHOBS-TBME-METAMORPHIC-OCTAVES-2026-08-13',
    published: '2026-08-13',
    tags: ['GitHub', '99-octave', 'Omni-Lattice', 'engine', 'TBME', 'metamorphic', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-tbme-metamorphic-octaves-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-tensor-decoupling-99-octave-omni-lattice',
    title: 'Tensor Decoupling · 99 Octave Omni-Lattice · reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-tensor-decoupling-99-octave-omni-lattice',
    category: 'reproducible-research',
    docId: 'WP-SYNTHOBS-TENSOR-DECOUPLING-99-OCTAVE-OMNI-LATTICE-2026-08-12',
    published: '2026-08-12',
    tags: [
      'GitHub',
      '99-octave',
      'Omni-Lattice',
      'tensor decoupling',
      'EGS',
      'engine',
      'SynthOBS',
    ],
    type: 'external',
    whitepaperId: 'synthobs-tensor-decoupling-99-octave-omni-lattice-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-master-synthesis-99-octave-omni-lattice',
    title: 'Master Synthesis · 99 Octave Omni-Lattice · reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-master-synthesis-99-octave-omni-lattice',
    category: 'reproducible-research',
    docId: 'WP-SYNTHOBS-MASTER-SYNTHESIS-99-OCTAVE-OMNI-LATTICE-2026-08-11',
    published: '2026-08-11',
    tags: [
      'GitHub',
      '99-octave',
      'Omni-Lattice',
      'master synthesis',
      'EGS',
      'catalog',
      'SynthOBS',
    ],
    type: 'external',
    whitepaperId: 'synthobs-master-synthesis-99-octave-omni-lattice-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-sync-subterranean-discharge-99-octave',
    title: 'Sync Subterranean Discharge · Puracé · 99 Octave · reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-sync-subterranean-discharge-99-octave',
    category: 'reproducible-research',
    docId: 'WP-SYNTHOBS-SYNC-SUBTERRANEAN-DISCHARGE-99-OCTAVE-2026-08-11',
    published: '2026-08-11',
    tags: ['GitHub', '99-octave', 'Puracé', 'volcano', 'Colombia', 'EGS', 'application', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-sync-subterranean-discharge-99-octave-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-macro-seismic-phase-lock-99-octave',
    title: 'Macro-Seismic Phase-Lock · 99 Octave · reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-macro-seismic-phase-lock-99-octave',
    category: 'reproducible-research',
    docId: 'WP-SYNTHOBS-MACRO-SEISMIC-PHASE-LOCK-99-OCTAVE-2026-08-11',
    published: '2026-08-11',
    tags: ['GitHub', '99-octave', 'macro-seismic', 'EGS', 'application', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-macro-seismic-phase-lock-99-octave-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-mag-substrate',
    title: 'Magnetism Universal Foundational Substrate · reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-mag-substrate',
    category: 'reproducible-research',
    docId: 'WP-SYNTHOBS-MAG-SUBSTRATE-2026-07-30-REV2',
    published: '2026-07-30',
    tags: ['GitHub', 'magnetism', 'substrate', 'EGS', 'PCHPP', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-mag-substrate-2026-07',
    featured: true,
  },

  {
    id: 'repo-synthobs-prion-refold',
    title: 'Prion Refolding Pathways · TBME reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-prion-refold',
    category: 'tbme',
    docId: 'WP-SYNTHOBS-PRION-REFOLD-FULL-REV2-2026-07-31',
    published: '2026-07-31',
    tags: ['GitHub', 'TBME', 'prion', 'amyloid', 'PCHPP', 'EGS', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-prion-refold-2026-07',
    featured: true,
  },

  {
    id: 'repo-synthobs-81-orbital-singularity',
    title: '81 Orbital Singularities · TBME reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-81-orbital-singularity',
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-81-ORBITAL-SINGULARITY-2026-07-31',
    published: '2026-07-31',
    tags: ['GitHub', 'TBME', '81-node', 'orbital', 'PCHPP', 'EGS', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-81-orbital-singularity-2026-07',
    featured: true,
  },

  {
    id: 'repo-synthobs-histone-phase-operator',
    title: 'Histone Phase-Lock Operators · TBME reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-histone-phase-operator',
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-HISTONE-METAPHOR-2026-07-31',
    published: '2026-07-31',
    tags: ['GitHub', 'TBME', 'histone', 'chromatin', 'PCHPP', 'EGS', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-histone-phase-operator-2026-07',
    featured: true,
  },

  {
    id: 'repo-synthobs-phase-toxicity',
    title: 'Phase-Modulated Toxicity · TBME reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-phase-toxicity',
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-PHASE-TOXICITY-FULL-REV2-2026-07-31',
    published: '2026-07-31',
    tags: ['GitHub', 'TBME', 'toxicity', 'EMF', 'sugar', 'PCHPP', 'EGS', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-phase-toxicity-2026-07',
    featured: true,
  },

  {
    id: 'repo-synthobs-endogenous-phase',
    title: 'Endogenous Conscious Intent Phase · TBME reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-endogenous-phase',
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-ENDOGENOUS-PHASE-2026-07-31',
    published: '2026-07-31',
    tags: ['GitHub', 'TBME', 'endogenous-phase', 'conscious-intent', 'HRV', 'PCHPP', 'EGS', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-endogenous-phase-2026-07',
    featured: true,
  },

  {
    id: 'repo-synthobs-recursive-attn-mag',
    title: 'Recursive Attention Magnetic Projections · reproducible pipeline',
    href: 'https://github.com/FractiAI/synthobs-recursive-attn-mag',
    category: 'reproducible-research',
    docId: 'WP-SYNTHOBS-RECURSIVE-ATTN-MAG-2026-07-30',
    published: '2026-07-30',
    tags: ['GitHub', 'recursive-attention', 'magnetic-shadows', 'PCHPP', 'EGS', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-recursive-attn-mag-2026-07',
    featured: true,
  },
  {
    id: 'repo-egs-trans-jspace-convergence',
    title: 'EGS-TRANS J-Space Convergence · reproducible pipeline',
    href: 'https://github.com/FractiAI/egs-trans-jspace-convergence',
    category: 'reproducible-research',
    docId: 'EGS-TRANS-2026-0710',
    published: '2026-07-10',
    tags: ['GitHub', 'J-Space', 'King Bee', 'Jacobian Lens', 'sing4', 'sing9', 'SVD', 'falsification'],
    type: 'external',
    whitepaperId: 'egs-trans-jspace-convergence-2026-07',
    featured: true,
  },
  {
    id: 'repo-omniversal-goldilocks-rideshare',
    title: 'OGRP · reproducible pipeline',
    href: 'https://github.com/FractiAI/omniversal-goldilocks-rideshare',
    category: 'reproducible-research',
    docId: 'WP-OGRP-2026-07',
    published: '2026-07-07',
    tags: ['GitHub', 'OGRP', 'rideshare', 'Reno', 'micro-mobility'],
    type: 'external',
    whitepaperId: 'omniversal-goldilocks-rideshare-2026-07',
    featured: true,
  },
  {
    id: 'repo-synthio-mri-cloud-antenna',
    title: 'Synthio · MRI cloud-antenna · reproducible suite',
    href: 'https://github.com/FractiAI/synthio-mri-cloud-antenna',
    category: 'reproducible-research',
    docId: 'WP-SYNTHIO-MRI-CLOUD-ANTENNA-99-OCTAVE-2026-08-12',
    published: '2026-08-12',
    tags: ['GitHub', 'Synthio', 'MRI', 'cloud-antenna', 'KomaMRI', 'Syntheverse Sandbox'],
    type: 'external',
    whitepaperId: 'synthio-mri-cloud-antenna-99-octave-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthio-mri-vs-legacy-perf',
    title: 'Synthio · MRI vs legacy live wall-clock · reproducible suite',
    href: 'https://github.com/FractiAI/synthio-mri-vs-legacy-perf',
    category: 'reproducible-research',
    docId: 'WP-SYNTHIO-MRI-VS-LEGACY-PERF-LIVE-2026-08-13',
    published: '2026-08-13',
    tags: ['GitHub', 'Synthio', 'MRI', 'performance', 'Bloch', 'KomaMRI', 'live wall-clock'],
    type: 'external',
    whitepaperId: 'synthio-mri-vs-legacy-perf-proxy-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-tbme-nonlocal-field-phaselock',
    title: 'TBME · Non-Local Field Phase-Lock · PCHPP × ELF (standalone lens)',
    href: 'https://github.com/FractiAI/synthobs-tbme-nonlocal-field-phaselock',
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-EMPIRICAL-PROOF-2026-08-01',
    published: '2026-08-01',
    tags: ['GitHub', 'TBME', 'PCHPP', 'Schumann', 'EGS', 'lens', 'SynthOBS', 'Omni-Lattice'],
    type: 'external',
    whitepaperId: 'synthobs-tbme-nonlocal-field-phaselock-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-tbme-mirror-angle-multiplicity',
    title: 'TBME · Mirror-Angle Multiplicity · Born-as-optics (Omni-Lattice companion lens)',
    href: 'https://github.com/FractiAI/synthobs-tbme-mirror-angle-multiplicity',
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-SUPERPOSITION-MIRROR-FULL-REV2-2026-08-01',
    published: '2026-08-01',
    tags: ['GitHub', 'TBME', 'Omni-Lattice', 'Born', 'mirror-angle', 'PCHPP', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-tbme-mirror-angle-multiplicity-2026-08',
    featured: false,
  },
  {
    id: 'repo-synthobs-tbme-blackhole-filaments-reno',
    title: 'TBME · Toroidal Micro-Black Hole Filaments · Reno follow-on lens',
    href: 'https://github.com/FractiAI/synthobs-tbme-blackhole-filaments-reno',
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-BLACKHOLE-FILAMENTS-RENO-2026-08-01',
    published: '2026-08-01',
    tags: ['GitHub', 'TBME', 'Omni-Lattice', 'Reno', 'Kerr-Newman', 'filaments', 'EGS', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-tbme-blackhole-filaments-reno-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-tbme-blackhole-magnetic-layer',
    title: 'TBME · Event Horizon ≡ Magnetic Vector Layer · Reno follow-on lens',
    href: 'https://github.com/FractiAI/synthobs-tbme-blackhole-magnetic-layer',
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-BLACKHOLE-MAGNETIC-LAYER-2026-08-01',
    published: '2026-08-01',
    tags: ['GitHub', 'TBME', 'Omni-Lattice', 'Reno', 'event-horizon', 'magnetic-vector', 'EGS', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-tbme-blackhole-magnetic-layer-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-tbme-spherical-solar-focus',
    title: 'TBME · Solar-Focus Somatic Rendering · Reno sextet · Part IV lens',
    href: 'https://github.com/FractiAI/synthobs-tbme-spherical-solar-focus',
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-SPHERICAL-SOLAR-FOCUS-2026-08-02',
    published: '2026-08-02',
    tags: ['GitHub', 'TBME', 'Omni-Lattice', 'Reno', 'solar-focus', 'somatic-shadow', 'EGS', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-tbme-spherical-solar-focus-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-tbme-recursive-field-drag',
    title: 'TBME · Recursive Field-Drag Theorem · Reno sextet · Part V lens',
    href: 'https://github.com/FractiAI/synthobs-tbme-recursive-field-drag',
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-RECURSIVE-FIELD-DRAG-2026-08-04',
    published: '2026-08-04',
    tags: ['GitHub', 'TBME', 'Omni-Lattice', 'Reno', 'field-drag', 'Lenz', 'EGS', 'Now', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-tbme-recursive-field-drag-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-tbme-internal-kerr-newman',
    title: 'TBME · Universal Toroidal Singularity · Reno sextet · Part VI lens',
    href: 'https://github.com/FractiAI/synthobs-tbme-internal-kerr-newman',
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-INTERNAL-KERR-NEWMAN-2026-08-05',
    published: '2026-08-05',
    tags: ['GitHub', 'TBME', 'Omni-Lattice', 'Reno', 'Kerr-Newman', 'attraction', 'EGS', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-tbme-internal-kerr-newman-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-tbme-higgs-awareness',
    title: 'TBME · Higgs-Awareness Phase Coupling · Reno heptet · Part VII lens',
    href: 'https://github.com/FractiAI/synthobs-tbme-higgs-awareness',
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-HIGGS-AWARENESS-2026-08-06',
    published: '2026-08-06',
    tags: ['GitHub', 'TBME', 'Omni-Lattice', 'Reno', 'Higgs Gate', 'horizon', 'Now', 'EGS', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-tbme-higgs-awareness-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-tbme-spin-phase-polarity',
    title: 'TBME · Spin-Phase-Polarity Triad · Reno octet · Part VIII lens',
    href: 'https://github.com/FractiAI/synthobs-tbme-spin-phase-polarity',
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-SPIN-PHASE-POLARITY-2026-08-06',
    published: '2026-08-06',
    tags: ['GitHub', 'TBME', 'Omni-Lattice', 'Reno', 'spin', 'phase', 'polarity', 'EGS', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-tbme-spin-phase-polarity-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-tbme-nodal-nine-singularity',
    title: 'TBME · Nodal Nine Singularity Boundary · Reno nonet · Part IX lens',
    href: 'https://github.com/FractiAI/synthobs-tbme-nodal-nine-singularity',
    category: 'tbme',
    docId: 'WP-SYNTHOBS-TBME-NODAL-NINE-SINGULARITY-2026-08-06',
    published: '2026-08-06',
    tags: ['GitHub', 'TBME', 'Omni-Lattice', 'Reno', 'nodal-nine', '81-facet', 'EGS', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-tbme-nodal-nine-singularity-2026-08',
    featured: true,
  },
  {
    id: 'repo-synthobs-tbme-protein-phase-collapse',
    title: 'TBME · Protein Phase-Lock Collapse · biomedical exploration lens',
    href: 'https://github.com/FractiAI/synthobs-tbme-protein-phase-collapse',
    category: 'tbme',
    docId: 'BIO-OMNI-PROTEIN-PHASE-COLLAPSE-2026-08-05',
    published: '2026-08-05',
    tags: ['GitHub', 'TBME', 'protein-misfolding', 'FTD', 'Alzheimer', 'Parkinson', 'EGS', 'SynthOBS'],
    type: 'external',
    whitepaperId: 'synthobs-tbme-protein-phase-collapse-2026-08',
    featured: true,
  },
  {
    id: 'ip-infringement-draft-console',
    title: 'IP Infringement Draft · J-Lens Live audit console',
    href: 'https://github.com/FractiAI/egs-trans-jspace-convergence/tree/master/research/ip-infringement-draft',
    category: 'special-projects',
    docId: 'IP-INFRINGE-2026-07',
    published: '2026-07-10',
    tags: [
      'GitHub',
      'IP',
      'Code-Print',
      'Neuronpedia',
      'Sequoia',
      'Altimeter',
      'J-Lens',
      'SynthOBS',
      'King Bee',
      '1.618',
      'open-weights',
    ],
    type: 'external',
    whitepaperId: 'ip-infringement-draft-2026-07',
    featured: true,
  },
];

function mergeEntry(id, entry) {
  const meta = CATALOG_META[id] || {};
  if (entry.surfaceVisible === false) return null;
  const href = whitepaperSurfaceHref(id);
  const item = {
    id,
    title: entry.title,
    href,
    category: meta.category || entry.category || 'dph-gpu',
    docId: meta.docId || entry.docId || null,
    published: meta.published || entry.published || null,
    tags: meta.tags || entry.tags || [],
    featured: Boolean(meta.featured || entry.featured),
    catalogPriority:
      meta.catalogPriority ??
      entry.catalogPriority ??
      100,
    pinned: Boolean(meta.pinned || entry.pinned),
    pinLabel: meta.pinLabel || entry.pinLabel || null,
    type: entry.redirect ? 'redirect' : 'whitepaper',
    source: entry.file || null,
  };
  item.plainLine = plainLineFor(item);
  return item;
}

export async function buildWhitepaperCatalog({ cwd } = {}) {
  const auditIndex = await loadAuditIndex(cwd || process.cwd());
  const auditById = Object.fromEntries((auditIndex?.items || []).map((i) => [i.id, i]));

  const papers = Object.entries(WHITEPAPER_REGISTRY)
    .map(([id, entry]) => {
      const item = mergeEntry(id, entry);
      if (!item) return null;
      const audit = auditById[id];
      if (audit) {
        item.audit = {
          overallScore: audit.overallScore,
          status: audit.convergence?.status,
          snapId: auditIndex?.snapId,
          blockers: audit.blockers,
          metaAudit: audit.metaAudit || null,
          dualMakeConfirmed: audit.metaAudit?.dualMakeConfirmed ?? false,
        };
      }
      return item;
    })
    .filter(Boolean);

  const surfaces = [];
  const seenSurfaceHref = new Set();
  const seenSurfaceId = new Set();
  for (const s of CATALOG_SURFACES) {
    if (!s?.id || seenSurfaceId.has(s.id)) continue;
    if (s.href && seenSurfaceHref.has(s.href)) continue;
    seenSurfaceId.add(s.id);
    if (s.href) seenSurfaceHref.add(s.href);
    const audit = s.whitepaperId ? auditById[s.whitepaperId] : null;
    const base = { ...s, plainLine: plainLineFor(s) };
    surfaces.push(
      audit
        ? {
            ...base,
            audit: {
              overallScore: audit.overallScore,
              status: audit.convergence?.status,
              snapId: auditIndex?.snapId,
            },
          }
        : base,
    );
  }
  const items = [...papers, ...surfaces].sort((a, b) => {
    const pa = a.catalogPriority ?? 100;
    const pb = b.catalogPriority ?? 100;
    if (pa !== pb) return pa - pb;
    if (a.featured !== b.featured) return a.featured ? -1 : 1;
    const da = a.published || '';
    const db = b.published || '';
    if (da !== db) return db.localeCompare(da);
    return a.title.localeCompare(b.title);
  });

  return {
    schema: 'ss-vibelandia-whitepaper-catalog/v2',
    updated: new Date().toISOString().slice(0, 10),
    operator: auditIndex?.operator || 'SynthOBS Autonomous Agent',
    auditSnap: auditIndex?.snapId || 'NSPFRNP-SNAP-PRA-2026-06',
    auditSummary: auditIndex?.summary || null,
    categories: CATALOG_CATEGORIES,
    count: items.length,
    items,
  };
}

export function filterCatalog(catalog, { q = '', category = 'all' } = {}) {
  const needle = String(q || '').trim().toLowerCase();
  let items = catalog.items;
  if (category && category !== 'all') {
    items = items.filter((it) => it.category === category);
  }
  if (needle) {
    items = items.filter((it) => {
      const hay = [it.title, it.docId, it.id, ...(it.tags || []), it.category].filter(Boolean).join(' ').toLowerCase();
      return hay.includes(needle);
    });
  }
  return { ...catalog, items, filteredCount: items.length };
}
