/** Old-school plain labels for Capitan's Bridge (no jargon wall). */

export const PLAIN = {
  masterCatalog: 'Sonic Singularity · full library',
  masterCatalogHint: 'Uploads land here. Your other playlists pull from this list.',
  yourPlaylists: 'Your playlists',
  myLikes: 'My Likes',
  myLikesHint: 'Built automatically from tracks you like.',
  likeTrack: 'Like track',
  unlikeTrack: 'Unlike track',
  listen: 'Listen',
  upload: 'Upload',
  play: 'Play',
  edit: 'Edit',
  editTrack: 'Edit track',
  deleteTrack: 'Delete track',
  songs: 'songs',
  tracks: 'tracks',
  totalTime: 'total time',
  freePreview: '30 seconds free on each song',
  fullPlay: 'full play',
  pickPlaylist: 'Pick a playlist on the left.',
  noTracksYet: 'No songs here yet. Go to Playlists, tap Edit, and add songs from the all-music list.',
  searchPlaylist: 'Search this playlist',
  filterTitle: 'Title / artist',
  filterTitlePlaceholder: 'Search title or artist…',
  filterGenre: 'Genre',
  filterAnyGenre: 'Any genre',
  filterPlaylist: 'Playlist',
  filterAnyPlaylist: 'Any playlist',
  filterInPlaylist: 'In playlist',
  filterNotInPlaylist: 'Not in playlist',
  filterPlaylistName: 'Which playlist',
  filterNoPlaylists: 'No playlists yet',
  sortBy: 'Sort by',
  sortAscending: 'Ascending order',
  sortDescending: 'Descending order',
  clearFilters: 'Reset filters',
  noFilterMatch: 'No tracks match these filters.',
  loadingCatalog: 'Loading your music…',
  noTracksUpload: 'No songs yet. Use Upload to add a track, then press play.',
} as const;
