/** Plain labels — SoundCloud-simple Listen experience. */

export const PLAIN = {
  library: 'Library',
  playlists: 'Playlists',
  playlist: 'Playlist',
  myLikes: 'Likes',
  myLikesHint: 'Tracks you heart show up here automatically.',
  myLikesEmpty: 'Heart a track to add it here.',
  listen: 'Listen',
  upload: 'Upload',
  uploadFirst: 'Upload your first track',
  questfest: 'QUESTFEST',
  playAll: 'Play all',
  editPlaylist: 'Edit',
  manageLibrary: 'Manage library',
  newPlaylist: 'New playlist',
  newNestedPlaylist: 'New playlist inside',
  nestedPlaylists: 'Playlists inside this one',
  addNestedPlaylist: 'Add playlist',
  removeNested: 'Remove from folder',
  emptyPlaylist: 'Empty playlist',
  likeTrack: 'Like',
  unlikeTrack: 'Unlike',
  play: 'Play',
  edit: 'Edit',
  editTrack: 'Edit track',
  editMasterCatalog: 'Edit library',
  deleteSelected: 'Delete selected',
  deleteTrack: 'Delete track',
  songs: 'songs',
  tracks: 'tracks',
  totalTime: 'total',
  freePreview: '30s preview',
  fullPlay: 'full play',
  pickPlaylist: 'Pick a playlist from the sidebar.',
  noTracksYet: 'No tracks here yet.',
  noSearchMatch: 'Nothing matches that search.',
  search: 'Search',
  searchPlaceholder: 'Search tracks…',
  refresh: 'Refresh',
  refreshing: 'Refreshing…',
  getPass: 'Get pass',
  captain: 'Captain',
  loading: 'Loading…',
  loadingCatalog: 'Loading…',
  noTracksUpload: 'Upload a track to get started.',
  /** Legacy keys still referenced elsewhere */
  masterCatalog: 'Library',
  masterCatalogHint: '',
  yourPlaylists: 'Playlists',
  filterTitle: 'Search',
  filterTitlePlaceholder: 'Search…',
  filterGenre: 'Genre',
  filterAnyGenre: 'Any',
  filterPlaylist: 'Playlist',
  filterAnyPlaylist: 'Any',
  filterInPlaylist: 'In playlist',
  filterNotInPlaylist: 'Not in playlist',
  filterPlaylistName: 'Playlist',
  filterNoPlaylists: 'No playlists',
  sortBy: 'Sort',
  sortAscending: 'Asc',
  sortDescending: 'Desc',
  clearFilters: 'Clear',
  noFilterMatch: 'No matches.',
  editMasterCatalogHint: '',
  noEditableTracks: 'Nothing to edit yet.',
  searchPlaylist: 'Search…',
} as const;
