/** Plain labels — SoundCloud-simple Listen experience. */

export const PLAIN = {
  library: 'Home',
  playlists: 'Playlists',
  playlist: 'Playlist',
  myLikes: 'Likes',
  myLikesHint: 'Tracks you heart show up here automatically.',
  myLikesEmpty: 'Heart a track to add it here.',
  listen: 'Listen',
  upload: 'Upload',
  uploadFirst: 'Upload your first track',
  questfest: 'QUESTFEST',
  playAll: 'Play all',
  editPlaylist: 'Edit',
  manageLibrary: 'Manage tracks',
  newPlaylist: 'New playlist',
  newNestedPlaylist: 'New playlist inside',
  nestedPlaylists: 'Playlists inside this one',
  addNestedPlaylist: 'Add playlist',
  removeNested: 'Remove from folder',
  emptyPlaylist: 'Empty playlist',
  likeTrack: 'Like',
  unlikeTrack: 'Unlike',
  addToPlaylist: 'Add to playlist',
  addToPlaylistHint: 'Use the list icon on each row to add tracks to your playlists.',
  play: 'Play',
  edit: 'Edit',
  editTrack: 'Edit track',
  editCover: 'Edit cover & description',
  changeCover: 'Change image',
  removeCover: 'Remove image',
  description: 'Description',
  descriptionPlaceholder: 'What is this playlist or track about?',
  playlistName: 'Name',
  save: 'Save',
  saving: 'Saving…',
  cancel: 'Cancel',
  saved: 'Saved.',
  saveFailed: 'Save failed — try again.',
  coverMustBeImage: 'Image must be JPEG, PNG, or WebP.',
  coverTooLarge: 'Image is too large — try a smaller file.',
  editMasterCatalog: 'Edit library',
  deleteSelected: 'Delete selected',
  deleteTrack: 'Delete track',
  songs: 'songs',
  tracks: 'tracks',
  totalTime: 'total',
  freePreview: '30s preview',
  freeFullPlay: '1 free full play',
  fullPlay: 'full play',
  shareTrack: 'Share track',
  shareCopied: 'Link copied — paste in WhatsApp, Messages, or your feed.',
  shareFailed: 'Could not share — try again.',
  removeFromPlaylist: 'Remove from playlist',
  pickPlaylist: 'Choose a playlist.',
  allTracks: "Hero Jo's Golden Bachdoor Hit Factory Master Catalog",
  noTracksYet: 'No tracks here yet.',
  noSearchMatch: 'Nothing matches that search.',
  search: 'Search',
  searchPlaceholder: 'Search tracks…',
  refresh: 'Refresh',
  refreshing: 'Refreshing…',
  getPass: 'Get pass',
  captain: 'Captain',
  loading: 'Loading…',
  loadingCatalog: 'Loading…',
  noTracksUpload: 'Upload a track to get started.',
  /** Legacy keys still referenced elsewhere */
  masterCatalog: 'Library',
  masterCatalogHint: '',
  yourPlaylists: 'Playlists',
  filterTitle: 'Search',
  filterTitlePlaceholder: 'Search…',
  filterGenre: 'Genre',
  filterAnyGenre: 'Any',
  filterPlaylist: 'Playlist',
  filterAnyPlaylist: 'Any',
  filterInPlaylist: 'In playlist',
  filterNotInPlaylist: 'Not in playlist',
  filterPlaylistName: 'Playlist',
  filterNoPlaylists: 'No playlists',
  sortBy: 'Sort',
  sortOrder: 'Playlist order',
  sortByName: 'Name',
  sortAscending: 'A→Z',
  sortDescending: 'Z→A',
  moveUp: 'Move up',
  moveDown: 'Move down',
  reorderHint: 'Drag ⋮⋮ or use arrows to reorder',
  clearFilters: 'Clear',
  noFilterMatch: 'No matches.',
  editMasterCatalogHint: '',
  noEditableTracks: 'Nothing to edit yet.',
  searchPlaylist: 'Search…',
} as const;
