#!/usr/bin/env python3
"""Generate all manuscript variables from the committed follow-up receipt."""
from __future__ import annotations

import json
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANUSCRIPT = ROOT / "docs" / "manuscript"
RECEIPT = ROOT / "data" / "openrouter-lattice-followup-deterministic.json"
STATS = ROOT / "data" / "openrouter-lattice-followup-statistics.json"


def f3(value: object) -> str:
    return f"{float(value):.3f}"


def comma(value: object) -> str:
    return f"{float(value):,.0f}"


def ci(block: dict) -> str:
    return f"[{f3(block['ci']['low'])}, {f3(block['ci']['high'])}]"


def metric_vars(block: dict, integer: bool = False) -> dict:
    return {
        "n": block["n"],
        "difference": comma(block["diff"]) if integer else f3(block["diff"]),
        "lattice_mean": comma(block["lattice"]["mean"]) if integer else f3(block["lattice"]["mean"]),
        "standard_mean": comma(block["standard"]["mean"]) if integer else f3(block["standard"]["mean"]),
        "lattice_ci": ci(block["lattice"]),
        "standard_ci": ci(block["standard"]),
        "paired_t": f"t={f3(block['pairedT']['t'])}; p={f3(block['pairedT']['p'])}; df={block['pairedT']['df']}",
        "wilcoxon": (f"W={block['wilcoxon']['W']}, p={f3(block['wilcoxon']['p'])} "
                     f"(n={block['wilcoxon']['n']} nonzero pairs)"),
        "cohens_dz": f3(block["cohensDz"]),
        "mde_note": block["mde"]["note"],
    }


def main() -> None:
    receipt = json.loads(RECEIPT.read_text())
    stats = json.loads(STATS.read_text())
    overall = receipt["overall"]
    n = receipt["repeats"] * len(receipt["tasks"])
    variables = {
        "metadata": {
            "title": "Lattice Chat Context Efficiency: Grounding, Token Economy, and Performance Boundaries",
            "author": "Daniel Ari Friedman", "affiliation": "Active Inference Institute",
            "email": "daniel@activeinference.institute", "orcid": "0000-0001-6232-9096",
            "version": "follow-up-1.0", "date_generated": date.today().isoformat(),
            "status": receipt["status"], "evidence_boundary": receipt["evidenceBoundary"],
        },
        "source": {"receipt": RECEIPT.relative_to(ROOT).as_posix(), "statistics": STATS.relative_to(ROOT).as_posix()},
        "experiment": {"model": receipt["model"], "repeats": receipt["repeats"], "tasks": len(receipt["tasks"]), "observations_per_treatment": n, "treatments": ", ".join(receipt["treatments"])},
        "primary": {
            "model": receipt["model"], "repeats": receipt["repeats"], "tasks": len(receipt["tasks"]), "observations_per_treatment": n,
            "lattice": {"accuracy": f3(overall["lattice"]["accuracy"]), "accuracy_count": f"{round(overall['lattice']['accuracy'] * n)}/{n}", "lenient_accuracy": f3(overall["lattice"]["accuracyLenient"]), "tokens": comma(overall["lattice"]["tokens"]), "latency_ms": comma(overall["lattice"]["latency"]), "tokens_per_correct": comma(overall["lattice"]["tokensPerCorrect"])},
            "standard": {"accuracy": f3(overall["standard"]["accuracy"]), "accuracy_count": f"{round(overall['standard']['accuracy'] * n)}/{n}", "lenient_accuracy": f3(overall["standard"]["accuracyLenient"]), "tokens": comma(overall["standard"]["tokens"]), "latency_ms": comma(overall["standard"]["latency"]), "tokens_per_correct": comma(overall["standard"]["tokensPerCorrect"])},
            "naive": {"accuracy": f3(overall["naive"]["accuracy"]), "accuracy_count": f"{round(overall['naive']['accuracy'] * n)}/{n}", "lenient_accuracy": f3(overall["naive"]["accuracyLenient"]), "tokens": comma(overall["naive"]["tokens"]), "latency_ms": comma(overall["naive"]["latency"]), "tokens_per_correct": comma(overall["naive"]["tokensPerCorrect"])},
            "lattice_naive_token_ratio": f3(overall["lattice"]["tokens"] / overall["naive"]["tokens"]),
            "lattice_naive_token_savings_percent": f3((1 - overall["lattice"]["tokens"] / overall["naive"]["tokens"]) * 100),
        },
        "statistics": {
            "accuracy": metric_vars(stats["metrics"]["accuracy"]),
            "accuracy_lenient": metric_vars(stats["metrics"]["accuracyLenient"]),
            "tokens": metric_vars(stats["metrics"]["tokens"], True),
            "latency": metric_vars(stats["metrics"]["latency"], True),
            "tokens_per_correct": metric_vars(stats["metrics"]["tokensPerCorrect"], True),
        },
        "tasks": {row["taskId"]: {t: {"accuracy": f3(row[t]["accuracy"]), "lenient_accuracy": f3(row[t]["accuracyLenient"]), "tokens": comma(row[t]["tokens"]), "latency_ms": comma(row[t]["latency"]), "tokens_per_correct": comma(row[t]["tokensPerCorrect"])} for t in receipt["treatments"]} for row in receipt["byTask"]},
    }
    vars_path = MANUSCRIPT / "manuscript_vars.yaml"
    vars_path.write_text("# Generated by scripts/z_generate_manuscript_variables.py; do not hand-edit.\n" + json.dumps(variables, indent=2) + "\n")
    config_path = MANUSCRIPT / "config.yaml"
    if config_path.is_file():
        config = config_path.read_text()
        config = config.replace('date: "{{metadata.date_generated}}"', f'date: "{variables["metadata"]["date_generated"]}"')
        config_path.write_text(config)
    print(f"wrote {vars_path}")


if __name__ == "__main__":
    main()
