import GoldilocksErdos.Syntheverse.EGS.Constants
import GoldilocksErdos.Syntheverse.EGS.Tactics
import GoldilocksErdos.Syntheverse.Security.Vacuity
import GoldilocksErdos.Witness.VanDerWaerden
import GoldilocksErdos.Witness.Schur
import GoldilocksErdos.Witness.ErdosStraus
import GoldilocksErdos.Catalog.VerifiedRows
